### ISSUE TITLE
Ability to enable / disable SAML Integration

### ISSUE THREAD

**Issue by rkadam** [rkadam/bitbucket-saml-plugin#8]
Right now, SAML integration is immediately enforced the moment plugin is installed. 

There are few situations we have found where you want to disable SAML integration and sign in as internal user. Specific Example where one need to log in as internal user is "to make changes to LDAP Directory". This is not allowed if you are user who logged in after authenticating against LDAP.

There are two asks here:
1. Provide admin interface to let Administrator decide if they like to enforce "SAML" integration.
2. In the event SAML integration is not enforced, "Login" page should disable another button "Use SAML Integration / Corporate Login".

**Current workaround (in case you want to login as internal user) is disable / uninstall plugin. Login as Internal User, do work that you wanted to perform. And then re-enable/re-install it the plugin again**.

**Comment by rjainm** [comment]
Please enable this feature. So we dont need to re-enable/re-install

**Comment by rkadam** [comment]
Hi there,

Can you please explain bit more on this? It will help to understand the
need.

Thank you,
Raju

**Comment by rkadam** [comment]
Plugin provides REST api which can be used to disable / enable the integration. Have you given a try using this feature?

Below you will find python code to use REST api. With use of REST API, you really dont have to disable / uninstall plugin. Hope this helps!
Raju

```import json
import requests
# Let's use internal user with ADMIN permissions for REST api calls
auth = ('admin-userid', 'password')
saml_config_url = 'https://<your-bitbucket-installation>/rest/samladmin/1.0/config'
  
headers = { 'X-Atlassian-Token': 'no-check', 'Content-Type': 'application/json'}
# 'true' will enforce SAML integration and 'false' will disable integration
config_data = {'enforceSSO' : 'true'}
response = requests.post(url=saml_config_url, auth=auth, data=json.dumps(config_data), headers=headers)
# status_code should be 204 with no content.
print response.status_code```
