### ISSUE TITLE
Q: How does it handle git http requests

### ISSUE THREAD

**Issue by llehn** [rkadam/bitbucket-saml-plugin#9]
Are all requests forced to go through SAML IdP? What happens when my git client connects to bitbucket, using http basic auth?

**Comment by rkadam** [comment]
Hi Lev -- Simply put, all browser based interactions will be routed to SAML IdP. It's recommended to use REST APIs if you dont want to enforced to go through SAML IdP.

Hope that clarifies.
Raju

**Comment by llehn** [comment]
So the API git client interact with are not SAML-authenticated then. Thanks for clarification.

**Comment by rkadam** [comment]
Right, API interactions are not SAML authenticated. Only Browser interaction entry points are.
